# 基础镜像
FROM python:3.12-slim AS builder
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 DEBIAN_FRONTEND=noninteractive
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources
WORKDIR /wheels
COPY requirements.txt requirements.txt
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ && \
    pip wheel --no-cache-dir --prefer-binary -r requirements.txt -w /wheels -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    apt-get purge -y --auto-remove gcc g++ && \
    rm -rf /var/lib/apt/lists/*

FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata procps iputil-ping curl vim && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt requirements.txt
COPY --from=builder /wheels /tmp/wheels
RUN pip install --no-cache-dir --no-index --find-links=/tmp/wheels -r requirements.txt && \
    rm -rf /tmp/wheels
RUN groupadd -r appuser && useradd -r -g appuser appuser
RUN mkdir -p /app/logs && chown -R appuser:appuser /app